name: Test GH_TOKEN Push

on:
  workflow_dispatch:

jobs:
  test-pat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout without default token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false
          fetch-depth: 0

      - name: Try pushing a tag with GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git tag test-pat-$(date +%s)
          git push origin --tags
